title: Resilient Responders
url: https://www.resilientresponders.sg
favicon: /images/EPSD_SHP_Logo.jpg
colors:
  primary-color: "#4372d6"
  secondary-color: "#49759a"
  media-colors:
    - title: media-color-one
      color: "#00838f"
    - title: media-color-two
      color: "#00838f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#6011a2"
    - title: media-color-five
      color: "#6011a2"
description: A Self-help Portal for Emergency Responders
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1oufkrfhunxzk.amplifyapp.com
prod: https://master.d1oufkrfhunxzk.amplifyapp.com
shareicon: /images/isomer-logo.svg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: resources
google_analytics_ga4: QXPSMWT66Y
